### ISSUE TITLE
zyp.yuepilon calculates sen slope on raw (not prewhitened) data

### ISSUE THREAD

**Issue by ateucher** [pacificclimate/zyp#2]
I hesitate to call this a bug, as it may be intentional behaviour, however I thought I would pose the question here:

In `zyp.yuepilon`, the Sen's slope (`trend`, as well as confidence limits `lbound` and `ubound`) that is returned is calculated on the raw input data (before autocorrelation is removed), while the Kendall's `tau` and `sig` is computed on the pre-whitened data. As such, this can lead to situations where the p-value (`sig`) computed by `Kendall` and the confidence limits on the Sen's slope do not agree (e.g., a p-value <= 0.05 while the confidence interval on the Sen's slope includes zero, or `sig` > 0.05 but the 95% confidence interval on the Sen's slope does not contain zero).

In `zyp.zhang` however, the Sen's slope is calculated on the final pre-whitened data, and these incongruities do not occur.

I'll open up a pull request with a potential fix.

**Comment by jameshiebert** [comment]
@AreliaTW Do you have any comments on this or opinions on what the intent is?

**Comment by ateucher** [comment]
Thanks very much @jameshiebert and @AreliaTW!
